# Generated by Django 5.0 on 2023-12-08 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_Cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='Product_cart/image'),
        ),
    ]
